ALTER TABLE events
  ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS checkin_last_synced_at TIMESTAMPTZ;

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS checkin_sync_error TEXT;
